### ISSUE TITLE
disregard whitespace at end of line for character names

### ISSUE THREAD

**Issue by acodispo** [chonger/cueballer#1]
Currently the names `RALPH     ` and `RALPH` are detected as 2 different characters.

**Comment by chonger** [comment]
So it twas and now it tw'aint - thanks for finding the bug!

**Comment by acodispo** [comment]
Thanks @chonger ! I know you & T have a todo list for this somewhere, but if it works for you I'll add any issues I notice here as I'm using the software.

I'm hoping to be able to help out in future, too, and send you some PRs!
